### ISSUE TITLE
Cannot find module: 'react-block-ui/redux'. Make sure this package is installed.

### ISSUE THREAD

**Issue by dprabu17** [Availity/react-block-ui#32] opened 2019-07-09 12:57 UTC
I am using redux and I used ReduxBlockUI in my form submission by refering the document https://availity.github.io/react-block-ui/components/ReduxBlockUi/ It's working fine but when I run 
**sudo npm run build**
I am facing the issue unable to get build directory.

> Failed to compile.
> Cannot find module: 'react-block-ui/redux'. Make sure this package is installed.
> You can install this package by running: yarn add react-block-ui/redux.

![Selection_218](https://user-images.githubusercontent.com/1658021/61209077-6b21b100-a716-11e9-8579-4ddfe2f3979c.png)

![Selection_217](https://user-images.githubusercontent.com/1658021/61208952-272eac00-a716-11e9-878a-57dc27f15b03.png)

**Comment by GoPro16** [comment] 2019-08-02 14:58
You should be able to import it from `react-block-ui/lib/redux`. Not sure if the docs are out of date or this is a build issue. Looking into this further.

**Comment by GoPro16** [comment] 2019-08-02 15:00
actually is a duplicate of #30

**Comment by GoPro16** [comment] 2019-08-14 14:41
fixed in `v1.3.1`

**Closed by GoPro16** 2019-08-14 14:41 UTC
