### ISSUE TITLE
Doesn’t block responsive design

### ISSUE THREAD

**Issue by NickLatin0** [Availity/react-block-ui#45] opened 2019-10-05 12:25 UTC
Works fine when the layout is standard with two components next to each other, but when the screen shrinks and the view goes responsive, the block UI only covers the top components. The bottom component is still editable

**Comment by TheSharpieOne** [comment] 2019-10-07 14:37
Can you post an example? You can fork this example and modify it to demo your issue: https://stackblitz.com/edit/react-block-ui?file=Example.js

**Comment by TheSharpieOne** [comment] 2020-01-31 21:18
I'm closing this since the the issue is no longer active. Please comment and it will be opened if you feel the issue has not been resolved / the question has not been answered.

**Closed by TheSharpieOne** 2020-01-31 21:18 UTC
Labels: invalid
