### ISSUE TITLE
ComponentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by prince272** [Availity/react-block-ui#59] opened 2021-02-22 12:44 UTC
These warnings keep showing:

react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: BlockUi

**Comment by mancioshell** [comment] 2021-12-28 11:54
Any Update?

**Comment by nylon22** [comment] 2021-12-28 16:14
looks like duplicate of #42 and #33

**Comment by nylon22** [comment] 2021-12-29 16:26
https://github.com/Availity/react-block-ui/issues/42#issuecomment-1002674899

**Closed** 2021-12-29 16:25 UTC
